openapi: 3.0.0
info:
  title: Hitcheed Laravel
  version: '1.0'
servers:
  - url: 'https://laravel.hitcheed.com/api/v1'
paths:
  /professionals:
    get:
      summary: /
      tags: []
      responses: {}
components:
  schemas: {}
