openapi: 3.0.0
info:
  title: Hitcheed Laravel
  version: '1.0'
servers:
  - url: 'https://laravel.hitcheed.com/api/v1'
paths:
  '/professionals/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /professionals:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
components:
  schemas: {}
